
from pydantic import BaseModel
from typing import List


class RAGQuery(BaseModel):
    """
    Model for a query to the RAG engine.
    """
    query: str                # The question or query text from the user
    stock: str                # The stock symbol (NVDA, TSLA, GOOG)


class RAGResponse(BaseModel):
    """
    Model for the response from the RAG engine.
    """
    response_text: str        # The financial advice generated by the LLM
    # List of article identifiers or titles used as context
    retrieved_articles: List[str]
